config/routes.rb
Rails.application.routes.draw do

  resources :images

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
   resources :advertisers  do
    member do
        get 'advertise_delete'
        put 'advertise_up'
  
      end
   end
  end
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :reports, only: :index do
        collection do
          get :sales_total_pdf
        end
      end
    end
  end

  
 

end

app/controllers/spree/admin/reports_controller.rb
module Spree
  module Admin
    class ReportsController < Spree::Admin::BaseController
      respond_to :html

      class << self
        def available_reports
          @@available_reports
        end

        def add_available_report!(report_key, report_description_key = nil)
          if report_description_key.nil?
            report_description_key = "#{report_key}_description"
          end
          @@available_reports[report_key] = {name: Spree.t(report_key), description: Spree.t(report_description_key)}
        end
      end

      def initialize
        super 
        ReportsController.add_available_report!(:sales_total)
      end

      def index
        @reports = ReportsController.available_reports
      end

      def sales_total
        params[:q] = {} unless params[:q]

        if params[:q][:completed_at_gt].blank?
          params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:completed_at_lt].blank?
          params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
        end

        params[:q][:s] ||= "completed_at desc"

        @search = Order.complete.ransack(params[:q])
        @orders = @search.result

        @totals = {}
        @orders.each do |order|
          @totals[order.currency] = { :item_total => ::Money.new(0, order.currency), :adjustment_total => ::Money.new(0, order.currency), :sales_total => ::Money.new(0, order.currency) } unless @totals[order.currency]
          @totals[order.currency][:item_total] += order.display_item_total.money
          @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
          @totals[order.currency][:sales_total] += order.display_total.money
        end
      end

      def sales_total_pdf
       params[:q] = {} unless params[:q]

        # if params[:q][:completed_at_gt].blank?
        #   params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
        # else
        #   params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        # end

        # if params[:q] && !params[:q][:completed_at_lt].blank?
        #   params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
        # end

        # params[:q][:s] ||= "completed_at desc"

        @search = Order.complete.ransack(params[:q])
        @orders = @search.result

        @totals = {}
        @orders.each do |order|
          @totals[order.currency] = { :item_total => ::Money.new(0, order.currency), :adjustment_total => ::Money.new(0, order.currency), :sales_total => ::Money.new(0, order.currency) } unless @totals[order.currency]
          @totals[order.currency][:item_total] += order.display_item_total.money
          @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
          @totals[order.currency][:sales_total] += order.display_total.money
        end
        render :pdf=>'sales_total_pdf'
      end

      private

      def model_class
        Spree::Admin::ReportsController
      end

      @@available_reports = {}

    end
  end
end

app/views/spree/admin/reports/sales_total.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:sales_totals) %>
<% end %>

<% content_for :page_actions do %>
  <%= back_to_list_button(Spree.t(:report), admin_reports_path) %>
<% end %>
<div class="well", style="align-text:left">
<%= link_to Spree.t(:pdf_report), {:contoller => "reports", :action => "sales_total_pdf"} , :target => '_blank', :class=> 'user_button' %>
</div>
  <%= render :partial => 'spree/admin/shared/report_order_criteria' %>
<table class="table table-bordered admin-report" data-hook="sales_total">
  <thead>
    <tr>
      <th><%= Spree.t(:currency) %></th>
      <th><%= Spree.t(:item_total) %></th>
      <th><%= Spree.t(:adjustment_total) %></th>
      <th><%= Spree.t(:sales_total) %></th>
    </tr>
  </thead>
  <tbody>
    <% @totals.each do |key, row| %>
      <tr>
        <td><%= key %></td>
        <td><%= row[:item_total].format %></td>
        <td><%= row[:adjustment_total].format %></td>
        <td><%= row[:sales_total].format %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<style>@media print {
  body {
    background: #FFF;
 }
}</style>

app/views/spree/admin/reports/sales_total_pdf.erb
<table border="1" style="width:100%; margin-top:100px; margin-left:50px; margin-right:50px">
  <thead>
    <tr>
      <td style="float:center" colspan="4" valign="middle" align="center"><%= Spree.t(:currency) %></td>
      <td style="float:center" colspan="4" valign="middle" align="center"><%= Spree.t(:item_total) %></td>
      <td style="float:center" colspan="4" valign="middle" align="center"><%= Spree.t(:adjustment_total) %></td>
      <td style="float:center" colspan="4" valign="middle" align="center"><%= Spree.t(:sales_total) %></td>
    </tr>
  </thead>
  <tbody>
    <% @totals.each do |key, row| %>
      <tr>
        <td style="float:center" colspan="4" valign="middle" align="center"><%= key %></td>
        <td style="float:center" colspan="4" valign="middle" align="center"><%= row[:item_total].format %></td>
        <td style="float:center" colspan="4" valign="middle" align="center"><%= row[:adjustment_total].format %></td>
        <td style="float:center" colspan="4" valign="middle" align="center"><%= row[:sales_total].format %></td>
      </tr>
    <% end %>
  </tbody>
</table>