config/routes.rb
Rails.application.routes.draw do

  resources :images

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
   resources :advertisers  do
    member do
        get 'advertise_delete'
        put 'advertise_up'
  
      end
   end
  end
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :reports, only: :index do
        collection do
          get :sales_total_pdf
        end
      end
    end
  end

  
 

end

app/models/spree/advertise.rb
module Spree
  class Advertise < ActiveRecord::Base
  	 belongs_to :user
        has_attached_file :image, :styles => { :medium => "150x150>", :thumb => "100x100>" }
    validates :description, presence: true
    validates :image, presence: true
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
 end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :language, :string, :default => 'rankspree'
end 

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    delegate_belongs_to :master, :sale_price
  end
end

app/controllers/spree/admin/reports_controller.rb
module Spree
  module Admin
    class ReportsController < Spree::Admin::BaseController
      respond_to :html

      class << self
        def available_reports
          @@available_reports
        end

        def add_available_report!(report_key, report_description_key = nil)
          if report_description_key.nil?
            report_description_key = "#{report_key}_description"
          end
          @@available_reports[report_key] = {name: Spree.t(report_key), description: Spree.t(report_description_key)}
        end
      end

      def initialize
        super 
        ReportsController.add_available_report!(:sales_total)
      end

      def index
        @reports = ReportsController.available_reports
      end

      def sales_total
        params[:q] = {} unless params[:q]

        if params[:q][:completed_at_gt].blank?
          params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
        else
          params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        end

        if params[:q] && !params[:q][:completed_at_lt].blank?
          params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
        end

        params[:q][:s] ||= "completed_at desc"

        @search = Order.complete.ransack(params[:q])
        @orders = @search.result

        @totals = {}
        @orders.each do |order|
          @totals[order.currency] = { :item_total => ::Money.new(0, order.currency), :adjustment_total => ::Money.new(0, order.currency), :sales_total => ::Money.new(0, order.currency) } unless @totals[order.currency]
          @totals[order.currency][:item_total] += order.display_item_total.money
          @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
          @totals[order.currency][:sales_total] += order.display_total.money
        end
      end

      def sales_total_pdf
       params[:q] = {} unless params[:q]

        # if params[:q][:completed_at_gt].blank?
        #   params[:q][:completed_at_gt] = Time.zone.now.beginning_of_month
        # else
        #   params[:q][:completed_at_gt] = Time.zone.parse(params[:q][:completed_at_gt]).beginning_of_day rescue Time.zone.now.beginning_of_month
        # end

        # if params[:q] && !params[:q][:completed_at_lt].blank?
        #   params[:q][:completed_at_lt] = Time.zone.parse(params[:q][:completed_at_lt]).end_of_day rescue ""
        # end

        # params[:q][:s] ||= "completed_at desc"

        @search = Order.complete.ransack(params[:q])
        @orders = @search.result

        @totals = {}
        @orders.each do |order|
          @totals[order.currency] = { :item_total => ::Money.new(0, order.currency), :adjustment_total => ::Money.new(0, order.currency), :sales_total => ::Money.new(0, order.currency) } unless @totals[order.currency]
          @totals[order.currency][:item_total] += order.display_item_total.money
          @totals[order.currency][:adjustment_total] += order.display_adjustment_total.money
          @totals[order.currency][:sales_total] += order.display_total.money
        end
        render :pdf=>'sales_total_pdf'
      end

      private

      def model_class
        Spree::Admin::ReportsController
      end

      @@available_reports = {}

    end
  end
end

app/controllers/spree/admin/taxons_controller.rb
module Spree
  module Admin
    class TaxonsController < Spree::Admin::BaseController

      before_action :load_taxonomy, only: [:create, :edit, :update]
      before_action :load_taxon, only: [:edit, :update]
      respond_to :html, :json, :js

      def index

      end

      def search
        if params[:ids]
          @taxons = Spree::Taxon.where(id: params[:ids].split(','))
        else
          @taxons = Spree::Taxon.limit(20).ransack(name_cont: params[:q]).result
        end
      end

      def create
        @taxon = @taxonomy.taxons.build(params[:taxon])
        if @taxon.save
          respond_with(@taxon) do |format|
            format.json { render json: @taxon.to_json }
          end
        else
          flash[:error] = Spree.t('errors.messages.could_not_create_taxon')
          respond_with(@taxon) do |format|
            format.html { redirect_to @taxonomy ? edit_admin_taxonomy_url(@taxonomy) : admin_taxonomies_url }
          end
        end
      end

      def edit
        @permalink_part = @taxon.permalink.split("/").last
      end

      def update
        parent_id = params[:taxon][:parent_id]
        set_position
        set_parent(parent_id)

        @taxon.save!

        # regenerate permalink
        regenerate_permalink if parent_id

        set_permalink_params

        #check if we need to rename child taxons if parent name or permalink changes
        @update_children = true if params[:taxon][:name] != @taxon.name || params[:taxon][:permalink] != @taxon.permalink

        if @taxon.update_attributes(taxon_params)
          flash[:success] = flash_message_for(@taxon, :successfully_updated)
        end

        #rename child taxons
        rename_child_taxons if @update_children

        respond_with(@taxon) do |format|
          format.html { redirect_to edit_admin_taxonomy_url(@taxonomy) }
          format.json { render json: @taxon.to_json }
        end
      end

      def destroy
        @taxon = Taxon.find(params[:id])
        @taxon.destroy
        respond_with(@taxon) { |format| format.json { render json: '' } }
      end

      private

      def taxon_params
        params.require(:taxon).permit(permitted_taxon_attributes)
      end

      def load_taxon
        @taxon = @taxonomy.taxons.find(params[:id])
      end

      def load_taxonomy
        @taxonomy = Taxonomy.find(params[:taxonomy_id])
      end

      def set_position
        new_position = params[:taxon][:position]
        if new_position
          @taxon.child_index = new_position.to_i
        end
      end

      def set_parent(parent_id)
        if parent_id
          @taxon.parent = Taxon.find(parent_id.to_i)
        end
      end

      def set_permalink_params
        if params.key? "permalink_part"
          parent_permalink = @taxon.permalink.split("/")[0...-1].join("/")
          parent_permalink += "/" unless parent_permalink.blank?
          params[:taxon][:permalink] = parent_permalink + params[:permalink_part]
        end
      end

      def rename_child_taxons
        @taxon.descendants.each do |taxon|
          reload_taxon_and_set_permalink(taxon)
        end
      end

      def regenerate_permalink
        reload_taxon_and_set_permalink(@taxon)
        @update_children = true
      end

      def reload_taxon_and_set_permalink(taxon)
        taxon.reload
        taxon.set_permalink
        taxon.save!
      end
    end
  end
end

app/controllers/spree/advertisers_controller.rb
module Spree
class AdvertisersController < Spree::BaseController
before_action :set_advertiser, only: [ :edit, :update, :destroy]
skip_before_action :authenticate_user

  # GET /advertises
  # GET /advertises.json
  def index
    @advertisers = Spree::Advertise.all
  end

  # GET /advertises/1
  # GET /advertises/1.json
  def show
    @advertiser = Spree::Advertise.find(params[:id])
  end

  # GET /advertises/new
  def new
    @advertiser = Spree::Advertise.new
  end

  # GET /advertises/1/edit
  def edit
    @advertiser = Spree::Advertise.find(params[:id])
  end

  # POST /advertises
  # POST /advertises.json
  def create
    @advertiser = Spree::Advertise.new(advertiser_params)
    respond_to do |format|
      if @advertiser.save
        format.html { redirect_to advertisers_url, notice: 'Advertiser was successfully created.' }
        format.json { render :show, status: :created, location: advertisers_url }
      else
        format.html { render :new }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /advertises/1
  # PATCH/PUT /advertises/1.json
  def update
    respond_to do |format|
      if @advertiser.update(advertiser_params)
        format.html { redirect_to advertisers_url, notice: 'Advertise was successfully updated.' }
        format.json { render :show, status: :ok, location: advertisers_url }
      else
        format.html { render :edit }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertises/1
  # DELETE /advertises/1.json
  def advertise_delete
  @advertiser = Spree::Advertise.find(params[:id])    
    @advertiser.delete
    redirect_to :action => 'index'
  end

  # def delete
  #   @advertisers = Spree::Advertise.find(params[:id])
  #   @advertisers.destroy()
  #   redirect_to :action => 'index'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertiser
      @advertiser = Spree::Advertise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertiser_params
      params.require(:advertise).permit(:header, :description, :image)
    end

  end

end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    
    def index
		   @taxons = Spree::Taxon.friendly
           return unless @taxons
           @advts = Spree::Advertise.all
    end
    
  end
end

app/controllers/spree/orders_controller_decorator.rb
module Spree
  Spree::OrdersController.class_eval do
     def cart
        unless @order.completed?
          @order.refresh_shipment_rates
        end
        if @order.shipments.shipped.count > 0
          redirect_to edit_admin_order_url(@order)
        end
      end
  end
end

app/helpers/spree/admin/base_helper.rb
module Spree
  module Admin
    module BaseHelper
      def flash_alert flash
        if flash.present?
          close_button = button_tag(class: 'close', 'data-dismiss' => 'alert', 'aria-label' => Spree.t(:close)) do
            content_tag('span', '&times;'.html_safe, 'aria-hidden' => true)
          end
          message = flash[:error] || flash[:notice] || flash[:success]
          flash_class = "danger" if flash[:error]
          flash_class = "info" if flash[:notice]
          flash_class = "success" if flash[:success]
          flash_div = content_tag(:div, (close_button + message), class: "alert alert-#{flash_class} alert-auto-disappear")
          content_tag(:div, flash_div, class: 'col-md-12')
        end
      end

      def field_container(model, method, options = {}, &block)
        css_classes = options[:class].to_a
        css_classes << 'field'
        if error_message_on(model, method).present?
          css_classes << 'withError'
        end
        content_tag(:div, capture(&block), class: css_classes.join(' '), id: "#{model}_#{method}_field")
      end

      def error_message_on(object, method, options = {})
        object = convert_to_model(object)
        obj = object.respond_to?(:errors) ? object : instance_variable_get("@#{object}")

        if obj && obj.errors[method].present?
          errors = safe_join(obj.errors[method], '<br />'.html_safe)
          content_tag(:span, errors, class: 'formError')
        else
          ''
        end
      end

      def datepicker_field_value(date)
        unless date.blank?
          l(date, format: Spree.t('date_picker.format', default: '%Y/%m/%d'))
        else
          nil
        end
      end

      def preference_field_tag(name, value, options)
        case options[:type]
        when :integer
          text_field_tag(name, value, preference_field_options(options))
        when :boolean
          hidden_field_tag(name, 0, id: "#{name}_hidden") +
          check_box_tag(name, 1, value, preference_field_options(options))
        when :string
          text_field_tag(name, value, preference_field_options(options))
        when :password
          password_field_tag(name, value, preference_field_options(options))
        when :text
          text_area_tag(name, value, preference_field_options(options))
        else
          text_field_tag(name, value, preference_field_options(options))
        end
      end

      def preference_field_for(form, field, options)
        case options[:type]
        when :integer
          form.text_field(field, preference_field_options(options))
        when :boolean
          form.check_box(field, preference_field_options(options))
        when :string
          form.text_field(field, preference_field_options(options))
        when :password
          form.password_field(field, preference_field_options(options))
        when :text
          form.text_area(field, preference_field_options(options))
        else
          form.text_field(field, preference_field_options(options))
        end
      end

      def preference_field_options(options)
        field_options = case options[:type]
        when :integer
          {
            size: 10,
            class: 'input_integer form-control'
          }
        when :boolean
          {}
        when :string
          {
            size: 10,
            class: 'input_string form-control'
          }
        when :password
          {
            size: 10,
            class: 'password_string form-control'
          }
        when :text
          {
            rows: 15,
            cols: 85,
            class: 'form-control'
          }
        else
          {
            size: 10,
            class: 'input_string form-control'
          }
        end

        field_options.merge!({
          readonly: options[:readonly],
          disabled: options[:disabled],
          size:     options[:size]
        })
      end

      def preference_fields(object, form)
        return unless object.respond_to?(:preferences)
        fields = object.preferences.keys.map { |key|
          if object.has_preference?(key)
            form.label("preferred_#{key}", Spree.t(key) + ": ") +
              preference_field_for(form, "preferred_#{key}", type: object.preference_type(key))
          end
        }
        safe_join(fields, '<br />'.html_safe)
      end

      # renders hidden field and link to remove record using nested_attributes
      def link_to_icon_remove_fields(f)
        url = f.object.persisted? ? [:admin, f.object] : '#'
        link_to_with_icon('delete', '', url, class: "spree_remove_fields btn btn-sm btn-danger", data: {action: 'remove'}, title: Spree.t(:remove)) + f.hidden_field(:_destroy)
      end

      def spree_dom_id(record)
        dom_id(record, 'spree')
      end

      I18N_PLURAL_MANY_COUNT = 2.1
      def plural_resource_name(resource_class)
        resource_class.model_name.human(count: I18N_PLURAL_MANY_COUNT)
      end

      def back_to_list_button(resource, path)
        button_text = Spree.t(:back_to_resource_list, resource: resource)
        link_to_with_icon 'arrow-left', button_text, path, class: 'btn btn-default'
      end

      private
        def attribute_name_for(field_name)
          field_name.gsub(' ', '_').downcase
        end
    end
  end
end

app/views/spree/advertisers/_form.html.erb
<%= form_for @advertiser, url: advertisers_path, html: { method: :post } do |f| %>

 <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="variant" class="form-group">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div data-hook="file" class="form-group">
    <%= f.label :image, Spree.t(:filename) %><br>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 4, :class => 'form-control' %>
  </div>
  </div>
  </div>
  <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), advertisers_path %>
    </div>
  
<% end %>

app/views/spree/advertisers/edit.html.erb
<h1>Editing Advertiser</h1>

<%= form_for @advertiser, url: advertiser_path, html: { method: :put } do |f| %>

 <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="variant" class="form-group">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div data-hook="file" class="form-group">
    <%= f.label :image, Spree.t(:filename) %><br>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 4, :class => 'form-control' %>
  </div>
  </div>
  </div>
  <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), advertisers_path %>
  </div>
  
<% end %>

app/views/spree/advertisers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="new_advertise" style="float:right;"><%= button_link_to(Spree.t(:new_advertisement), spree.new_advertiser_path(@advertiser), { class: "btn-success", icon: 'add'}) %></div>
<h1>Listing Advertisers</h1>

<table class="table sortable" data-hook="images_table" >
  <thead>
    <tr data-hook="images_header">
        <th colspan="1">Header</th>
      <th>Description</th>
      <th>Image</th>
      <td class="actions actions-2 text-center">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% unless @advertisers.nil? %>
    <% @advertisers.each do |advertiser| %>
      <tr  data-hook="images_row">
        <td><%= advertiser.header %></td>
        <td><%= advertiser.description %></td>
        <td class="image"><%= image_tag(advertiser.image, :size => "80x80") if advertiser.image?  %></td>
        <td class="actions actions-3 text-center"><%= link_to 'Edit', edit_advertiser_path(advertiser) %>
       <%= link_to 'Show', advertiser_path(advertiser) %>
       <%= link_to 'Delete', advertise_delete_advertiser_path(advertiser) %></td>
        
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>


<style >
     h1 {
     color: #8E8EB9;
     }
</style>

app/views/spree/advertisers/new.html.erb
<h1>New Advertiser</h1>

<%= form_for @advertiser, url: advertisers_path, html: { method: :post } do |f| %>

 <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="variant" class="form-group">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div data-hook="file" class="form-group">
    <%= f.label :image, Spree.t(:filename) %><br>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 4, :class => 'form-control' %>
  </div>
  </div>
  </div>
  <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), advertisers_path %>
    </div>
  
<% end %>

app/views/spree/advertisers/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Header:</strong>
  <%= @advertiser.header %>
</p>

<p>
  <strong>Description:</strong>
  <%= @advertiser.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@advertiser.image, :size => "280x280") if @advertiser.image?  %>
</p>

<%= link_to 'Edit', edit_advertiser_path(@advertiser) %>
<%= link_to 'Back', advertisers_path %>